#!/bin/bash
# Program untuk menghapus tools ini

# ----- The X Team -----

#

# Coded by: The X Kuhaku

#  * https://github.com/The-X-Team-Debug/

# project!
#
# -------------------------

clear

echo "

";

if [ "$PREFIX" = "/data/data/com.termux/files/usr" ]; then

    INSTALL_DIR="$PREFIX/usr/share/doc/Kuhaku"

    BIN_DIR="$PREFIX/bin/"

    BASH_PATH="$PREFIX/bin/bash"

    TERMUX=true

elif [ "$(uname)" = "Darwin" ]; then

    INSTALL_DIR="/usr/local/Kuhaku"

    BIN_DIR="/usr/local/bin/"

    BASH_PATH="/bin/bash"

    TERMUX=false

else

    INSTALL_DIR="$HOME/.Kuhaku"

    BIN_DIR="/usr/local/bin/"

    BASH_PATH="/bin/bash"

    TERMUX=false

fi

echo "[✔] Memeriksa directories...";

if [ -d "$INSTALL_DIR" ]; then

        rm -rf "$INSTALL_DIR"

        rm "$BIN_DIR/Kuhaku*"

        rm -rf "$INSTALL_DIR"

        rm "$BIN_DIR/Kuhaku*"

    else

        echo "[✘] If you want to uninstall you must remove previous installations [✘] ";

        echo "[✘] Failed! [✘] ";

fi

echo "[✔] Cleaning up old directories...";

if [ -d "$ETC_DIR/Kuhaku" ]; then

    echo "$DIR_FOUND_TEXT"

    if [ "$TERMUX" = true ]; then

        rm -rf "$ETC_DIR/Kuhaku"

    else

        sudo rm -rf "$ETC_DIR/Manisso"

    fi

fi

clear

clear

echo "[✔] all good!"
